### ISSUE TITLE
"Open URL in a new tab" opens URL in current tab too

### ISSUE THREAD

**Issue by hutorny** [jakubboucek/kill-fbclid#5]
kill-fbclid affects Chrome's "Open URL in a new tab" which opens URL in current tab too.
STR:
1. Open an FB page
2. Right-click on a link
3. Select option "Open URL in a new tab"
AR:
Both new tab and curren open selected link.
ER:
Selected link opened only in a new tab, Current tab remains intact

**Comment by damnms** [comment]
the new opened tab is with fbclid, the current page does open the new link without fbclid.
the last problem is even worse for me, thats the reason why i guess i will uninstall this addon. 
when i read on facebook something and rightclick -> open new tab something, the current page is gone, including all comments of me (because i did not send them yet as i did not expect to lose the tab). i so often had 2-3 pictures with a interesting headline, i open one of them in a new tab, booom, all gone.

**Comment by jakubboucek** [comment]
Duplicity of #3, please use [Basic variant of extension](https://chrome.google.com/webstore/detail/kill-fbclid/jlmdkcaiejonohbmkgickmkgbpceokmn)
